id: a361d7cd2ff54baba7b9eb6a7cdfc8a2
initial_creation_type: ocr
source_metadata:
  volumes:
    983ae981077742a0af5c945c26837f8b:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
