id: D9D59488D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:20:21+00:00'
last_modified: '2022-05-26T10:35:16.098468+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    d078:
      image_group_id: I1PD95869
      title: སྲུང་བའི་འཁོར་ལོ་སྒྲུབ་པའི་ཐབས།
      total_pages: 1586
      order: 24
      base_file: d078.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
